### PR TITLE
configure.ac: dont break if dcadec is missing, dcadec is a ffmpeg dep

### PR DESCRIPTION
**Pull request by sraue**
ping @fritsch @wsnipex

btw: do we really need the dcdec check in kodi's configure, because its a ffmpeg dep and nothing in kodi byself really depends on dcsdec headers and libs?

### CODE REVIEW

**Comment by wsnipex** [comment]
we do need the check since we link ffmpeg static and therefore need possible depends of dcadec as well(same as for e.g. gnutls). Currently it wouldn't be an issue as libdcadec seems to be static only without any depends, but once linux distros pick it up or the lib evolves, we might have to deal with shared libs as well.
FFmpeg will fail if dcadec is not found, so we really should keep the error here.

**Comment by sraue** [comment]
this means we cant anymore build without dcadec (if we dont want/need dcadec support) this should be optional... for me it breaks projects where dcadec is disabled (for various resons)... thats why i ask if the whole check must be in kodis configure (in OpenELEC dcadec support is optional, but enabled now for all projects)

**Comment by wsnipex** [comment]
you'd have to change ffmpeg to autodetect dcadec. Currently it seems to default to off

**Comment by sraue** [comment]
see https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/multimedia/ffmpeg/package.mk#L52 and https://github.com/OpenELEC/OpenELEC.tv/blob/master/projects/Generic/options#L85

**Comment by wsnipex** [comment]
yeah, thats not in kodi though ;) To support that you could make our configure auto detect dcadec and only fail if --enable-dcadec was given. 
Otoh, whats the reason you want to disable it? It has a GUI option to turn it off anyway.

**Comment by sraue** [comment]
not for all devices and for AML devices it seems to not work (yet), also there are own (or commercial) projects who dont need this and want it stripped.
generally i dont see a reason we must have configure opts and checks if for librarys kodi dont link against... should not be something like this part of the ffmpeg depends scripts instead?

**Comment by wsnipex** [comment]
I already said, we need to link against all libs ffmpeg links against. It might work without it atm(I didn't check), but it won't once dcadec needs some dependencies.
Those commercial projects are not our concern, they can easily patch it out.

**Pull request closed without merging**
