### PR TITLE
Apply ffmpeg patches automatically after downloading and extracting ffmpeg tarball

### PR DESCRIPTION
**Pull request by nsenica**
## Description
Auto patches ffmpeg source on CMake builds.

## Motivation and Context
Current CMake build don't patch ffmpeg source, this change makes it possible to.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by nsenica** [comment]
@popcornmix any chance this gets merged into your backports ? Thanks.

**Comment by popcornmix** [comment]
Sorry I missed this originally. I don't think many users are building ffmpeg with cmake on Krypton so should be fairly safe.

**Comment by nsenica** [comment]
@popcornmix Sorry to bother, but is there any reason why this is not included anymore in this branch ? :) 

Also: 2fde976 and b6ba019 are not :(

**Comment by popcornmix** [comment]
https://github.com/popcornmix/xbmc/commit/b6ba01992ec332de913585bdcba612a684bb47c0 has been merged upstream: https://github.com/xbmc/xbmc/pull/11521

https://github.com/popcornmix/xbmc/commit/2fde976fb0a7257eabfc56422b6fcfe1d98b135f looks to be present here: https://github.com/popcornmix/xbmc/commit/cdc528d79b99a1cc90d1828f56a46234fd685c9a

This PR's commit seems to be missing - I've added it now.

**Comment by nsenica** [comment]
Makes sense :) I didn't realise the other two were already included.

Thanks for the explanation :)

**Pull request merged**
