### PR TITLE
Rebase ffmpeg patches and hack kernel defines

### PR DESCRIPTION
**Pull request by graysky2**
* Rebase ffmpeg patches on top 4.3.2-Matrix-19.1
* Define V4L2_PIX_FMT_NV12_10_COL128 and V4L2_PIX_FMT_NV12_COL128

Adding these fixes build issues on Arch ARM detailed [here](https://forum.kodi.tv/showthread.php?tid=362490) and fixed in https://github.com/archlinuxarm/PKGBUILDs/commit/88146a95d9478ebe162896b0745a46274f064914
Credit to @dobo90

## Description
Add several kernel defines to patch

## Motivation and Context
Greatly simplifies builds on Arch ARM

## How Has This Been Tested?
Builds on Arch ARM, aarch64 and armv7h

## Types of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by popcornmix** [comment]
These really need to go to this repo https://github.com/jc-kynesim/rpi-ffmpeg/tree/dev/4.3.1/drm_prime_1 where the patches come from. Otherwise they will be lost on the next update.
But I suspect there may be resistance as this is a hack and when this code is finally merged into ffmpeg they won't be allowed.
The defines should go into `drm_fourcc.h` in the distribution's `/usr/include`

**Comment by graysky2** [comment]
1) Are you sure about `V4L2_PIX_FMT_NV12_10_COL128` and `V4L2_PIX_FMT_NV12_COL128` being defined in `/usr/include/libdrm/drm_fourcc.h`?  When I grep for `V4L2_PIX_FMT_NV12_10_COL128` it is found in `/usr/include/linux/videodev2.h` but only if I build the api-headers from the rpi-5.10.y source tree; building the generic linux tree produces a file without them entirely.

2) Any thoughts as to these getting upstreamed?  Maintaining two api-header packages, one built from vanilla and one built from rpi-5.10.y is a bit problematic.

**Comment by graysky2** [comment]
1) Are you sure about `V4L2_PIX_FMT_NV12_10_COL128` and `V4L2_PIX_FMT_NV12_COL128` being defined in `/usr/include/libdrm/drm_fourcc.h`?  When I grep for it I get no hits:
```
% grep -r V4L2_PIX_FMT_NV12_10_COL128 /usr/include
% echo $?
1
```
However, I do find it but only if I build **linux-api-headers** from the rpi-5.10.y source tree; building the generic linux tree produces a file without them entirely.
```
% grep -r V4L2_PIX_FMT_NV12_10_COL128 linux-raspberrypi-api-headers 
linux-raspberrypi-api-headers/usr/include/linux/videodev2.h:#define V4L2_PIX_FMT_NV12_10_COL128 v4l2_fourcc('N', 'C', '3', '0')
```

For reference, below are copies of `/usr/include/linux/videodev2.h` provided by two difference sources:
* [Here](https://gist.github.com/graysky2/032458cfa8a65643ae4f6d2123b50661) built from the standard linux-api-headers package (ie built from vanilla kernel source).
* [Here](https://gist.github.com/graysky2/5fc94ea0150b9ef003c2579f2728ee16) built from a modified linux-api-headers package (build from rpi-5.10.y kernel source).

Finally, [here](https://gist.github.com/graysky2/c80273c2acfb74610fc4012562be9237) is a diff comparing the two for illustrative purposes.

2) Any thoughts as to these getting upstreamed?  Maintaining two api-header packages, one built from vanilla and one built from rpi-5.10.y is a bit problematic.

**Comment by graysky2** [comment]
Can you walk me through how you generated https://github.com/popcornmix/xbmc/blob/gbm_matrix/tools/depends/target/ffmpeg/0001-rpi-Add-hevc-acceleration.patch on the shell?

**Comment by graysky2** [comment]
I'll close this since as you pointed out, John Cox is upstream.

**Comment by graysky2** [comment]
@popcornmix - Can you describe how you generated `tools/depends/target/ffmpeg/0001-rpi-Add-hevc-acceleration.patch`

```
git clone git@github.com:jc-kynesim/rpi-ffmpeg.git
cd rpi-ffmpeg
git remote add xbmc git@github.com:xbmc/FFmpeg.git
git fetch xbmc
git checkout dev/4.3.1/drm_prime1
git diff xbmc/release/4.3-kodi > 0001-rpi-Add-hevc-acceleration.patch
```

Is that right?  When I did it, the resulting file was not the same as your file currently in gbm_matrix.

**Comment by popcornmix** [comment]
I have remotes:
```
xbmc	https://github.com/xbmc/FFmpeg.git`
jc_kynesim	https://github.com/jc-kynesim/rpi-ffmpeg.git
```
and generate patch with
```
git checkout jc_kynesim/dev/4.3.1/drm_prime_1
git diff xbmc/release/4.3-kodi > ~/buster/home/pi/projects/kodi/kodi_gbm/tools/depends/target/ffmpeg/0001-rpi-Add-hevc-acceleration.patch
```

**Pull request closed without merging**
